//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpComicViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpComicViewer.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BookmarkManager_Name {
            get {
                return ResourceManager.GetString("BookmarkManager_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ContextMenu_About {
            get {
                return ResourceManager.GetString("ContextMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bookmark.
        /// </summary>
        internal static string ContextMenu_AddBookmark {
            get {
                return ResourceManager.GetString("ContextMenu_AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to height.
        /// </summary>
        internal static string ContextMenu_FitToHeight {
            get {
                return ResourceManager.GetString("ContextMenu_FitToHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to screen.
        /// </summary>
        internal static string ContextMenu_FitToScreen {
            get {
                return ResourceManager.GetString("ContextMenu_FitToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to width.
        /// </summary>
        internal static string ContextMenu_FitToWidth {
            get {
                return ResourceManager.GetString("ContextMenu_FitToWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string ContextMenu_Fullscreen {
            get {
                return ResourceManager.GetString("ContextMenu_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage bookmarks.
        /// </summary>
        internal static string ContextMenu_ManageBookmarks {
            get {
                return ResourceManager.GetString("ContextMenu_ManageBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ContextMenu_Normal {
            get {
                return ResourceManager.GetString("ContextMenu_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ContextMenu_Open {
            get {
                return ResourceManager.GetString("ContextMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume reading.
        /// </summary>
        internal static string ContextMenu_ResumeReading {
            get {
                return ResourceManager.GetString("ContextMenu_ResumeReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View modes.
        /// </summary>
        internal static string ContextMenu_ViewModes {
            get {
                return ResourceManager.GetString("ContextMenu_ViewModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark added.
        /// </summary>
        internal static string Notification_BookmarkAdded {
            get {
                return ResourceManager.GetString("Notification_BookmarkAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to height.
        /// </summary>
        internal static string Notification_FitToHeight {
            get {
                return ResourceManager.GetString("Notification_FitToHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to screen.
        /// </summary>
        internal static string Notification_FitToScreen {
            get {
                return ResourceManager.GetString("Notification_FitToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to width.
        /// </summary>
        internal static string Notification_FitToWidth {
            get {
                return ResourceManager.GetString("Notification_FitToWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Notification_Normal {
            get {
                return ResourceManager.GetString("Notification_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get next page.
        /// </summary>
        internal static string Notification_UnableToGetNextPage {
            get {
                return ResourceManager.GetString("Notification_UnableToGetNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get previous page.
        /// </summary>
        internal static string Notification_UnableToGetPreviousPage {
            get {
                return ResourceManager.GetString("Notification_UnableToGetPreviousPage", resourceCulture);
            }
        }
    }
}
